# author: Rukia
workpath = ''
cachepath = ''
datapath = '/home/rukia/cq/data/'
asset_card_path = '/home/rukia/cq/data/image/assets/cards/'
asset_card_thumb_path = '/home/rukia/cq/data/image/assets/cards/thumb/'
asset_event_path = '/home/rukia/cq/data/image/assets/events/'
asset_gacha_path = '/home/rukia/cq/data/image/assets/gachas/'
asset_resource_path = '/home/rukia/cq/data/image/assets/res/'